### ISSUE TITLE
Cant link my WE and KDE plugin

### ISSUE THREAD

**Issue by VXEAD** [catsout/wallpaper-engine-kde-plugin#319] opened 2023-08-17 15:55 UTC
Hi, i cant found folder that i need add to library to correct work of WE plugin
Steam (Flatpak Edition) folder /home/pcname/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/wallpaper_engine/ 
Thats right?
And my wallpaper storage on steam cloud, thats can be issues with this?
![image](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/103393069/1acd51a0-32b4-477a-b78e-7eb9d035681f)

![image](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/103393069/3f83a575-c5ac-4d4f-862f-c80df79c632e)

**Comment by VXEAD** [comment] 2023-08-17 15:56
> Hi, i cant found folder that i need add to library to correct work of WE plugin Steam (Flatpak Edition) folder /home/pcname/.var/app/com.valvesoftware.Steam/.local/share/Steam/steamapps/common/wallpaper_engine/ Thats right? And my wallpaper storage on steam cloud, thats can be issues with this?

![image](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/103393069/471f7ee7-78a5-4941-9c17-84d8adae99fe)

**Comment by Impqxr** [comment] 2023-08-17 22:10
the right path is `/home/pcname/.var/app/com.valvesoftware.Steam/.local/share/Steam/` and your wallpapers saved locally(`../steamapps/workshop`)

**Comment by VXEAD** [comment] 2023-08-18 09:42
> the right path is `/home/pcname/.var/app/com.valvesoftware.Steam/.local/share/Steam/` and your wallpapers saved locally(`../steamapps/workshop`)

![image](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/103393069/2c97c2b7-7c08-4c83-b1d6-4050fcd1d5fe)
i need to install it? if yes how i can do it?

**Comment by VXEAD** [comment] 2023-08-18 11:25
> the right path is `/home/pcname/.var/app/com.valvesoftware.Steam/.local/share/Steam/` and your wallpapers saved locally(`../steamapps/workshop`)

btw i make like on this https://github.com/catsout/wallpaper-engine-kde-plugin/issues/75 but 
![image](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/103393069/a40ede76-cc8a-4455-a859-f1b4f64c1438)

**Comment by Impqxr** [comment] 2023-08-18 16:39
what's your distribution? you can try `apt update`

**Comment by VXEAD** [comment] 2023-08-18 17:02
> what's your distribution? you can try `apt update`

debian 12.1

**Comment by Impqxr** [comment] 2023-08-19 13:35
try `apt install libqt5websockets5`

**Comment by Impqxr** [comment] 2023-08-19 13:39
try `apt install qml-module-qtwebsockets`

**Comment by VXEAD** [comment] 2023-08-20 13:17
> 

![image](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/103393069/525b20ed-2fab-4e56-8d96-ea1f858a5963)
now i have this error
and this on my desktop 
![image](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/103393069/da8db3ab-6779-4919-9716-6c3c236d0c4c)

**Comment by Impqxr** [comment] 2023-08-20 15:05
`apt install python3-websockets`

**Comment by VXEAD** [comment] 2023-08-20 15:12
> `apt install python3-websockets`

![image](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/103393069/fdb63806-640c-4b51-ace5-79accba70607)
by /home/pcname/.var/app/com.valvesoftware.Steam/.local/share/Steam/

**Comment by Impqxr** [comment] 2023-08-20 15:16
> > `apt install python3-websockets`
> 
> ![image](https://user-images.githubusercontent.com/103393069/261860288-fdb63806-640c-4b51-ace5-79accba70607.png) by /home/pcname/.var/app/com.valvesoftware.Steam/.local/share/Steam/

select other filters and click refresh
![image](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/70816395/cbc7c990-34f0-4d17-b3f9-fc931f7fb762)

**Comment by Impqxr** [comment] 2023-08-20 15:29
if the problem is solved, please close the issue

**Comment by VXEAD** [comment] 2023-08-20 15:41
> if the problem is solved, please close the issue

![image](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/103393069/0da68d55-283f-4778-b5a0-ce4de4f786ae)
all will be selected, but same problem before

**Comment by Impqxr** [comment] 2023-08-20 15:41
> > if the problem is solved, please close the issue
> 
> ![image](https://user-images.githubusercontent.com/103393069/261861848-0da68d55-283f-4778-b5a0-ce4de4f786ae.png) all will be selected, but same problem before

do not select Favorite

**Comment by VXEAD** [comment] 2023-08-20 15:44
> > > if the problem is solved, please close the issue
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/103393069/261861848-0da68d55-283f-4778-b5a0-ce4de4f786ae.png) all will be selected, but same problem before
> 
> do not select Favorite

yeah now its work, but 
![image](https://github.com/catsout/wallpaper-engine-kde-plugin/assets/103393069/2cf80075-e445-42b2-a343-6cd01aa04cfd)
if u can help me with this command i will be so happy!

**Comment by Impqxr** [comment] 2023-08-20 15:48
you need to compile this plugin. copy the commands from [Dependencies](https://github.com/catsout/wallpaper-engine-kde-plugin#dependencies) for **Debian** and [Build and Install](https://github.com/catsout/wallpaper-engine-kde-plugin#build-and-install)

**Closed** 2023-08-20 15:51 UTC
