### ISSUE TITLE
"Sorry, but your browser does not support WebGL" ?

### ISSUE THREAD

**Issue by Cicango** [catsout/wallpaper-engine-kde-plugin#194] opened 2022-06-23 14:02 UTC
Hi,
tried to set a web wallpaper on and got this message:

"Sorry, but your browser does not support WebGL", how to fix?

regards

**Comment by Technetium1** [comment] 2022-08-08 18:42
Duplicate of #44

**Closed** 2022-08-26 00:52 UTC
